### ISSUE TITLE
Sig figs and zooming

### ISSUE THREAD

**Issue by veillette** [phetsims/calculus-grapher#104]
While values enabled (in preference dialog), we can zoom in and out of a graph.
Eventually we come across this
![image](https://user-images.githubusercontent.com/7633344/201981758-9387aa85-a945-462f-a0ed-c1f7b7a09546.png)

**Comment by pixelzoom** [comment]
@veillette and I discussed this in our 11/15 meeting.  

* @veillette  has an approach that he's using that looks good, and doesn't need the complexity of the Fourier approach.  So he'll continue doing what he's doing.

* The layout issue shown in https://github.com/phetsims/calculus-grapher/issues/104#issue-1450109399 is weird. We took a quick look, but did not immeditely figure it out.  Regardless, a better approach may be to create a new TickLabelSet when the range changes, so @veillette will try that.

**Comment by veillette** [comment]
In the commits above I created a new TickLabelSet when the vertical range changes. I hoisted the creation of the tickLabelSet into a private method. 

````js
 /**
   * Returns a TickLabelSet that appear on the left hand side of the chart.
   * Responsible for determining the appropriate number of decimal places for the label
   *
   * @param spacing - the separation ( in model coordinates) of the labels
   */
  private getVerticalTickLabelSet( spacing: number ): TickLabelSet {

    // the number of decimal places for the labels
    let decimalPlaces: number;

    if ( Number.isInteger( spacing ) ) {

      // the number of decimal is zero since the labels are multiple of integers
      decimalPlaces = 0;
    }
    else if ( Number.isInteger( spacing * 10 ) ) {

      // the spacing has only one decimal
      decimalPlaces = 1;
    }
    else {

      // two decimal places is sufficient for our zoom range
      decimalPlaces = 2;
    }


    return new TickLabelSet( this.chartTransform, Orientation.VERTICAL, spacing,
      {
        value: CalculusGrapherConstants.CURVE_X_RANGE.min,
        createLabel: ( value: number ) =>
          new Text( Utils.toFixed( value, decimalPlaces ), { fontSize: 8 } ),
        positionLabel: ( label: Node, tickBounds: Bounds2 ) => {
          label.rightCenter = tickBounds.leftCenter.minusXY( 1, 0 );
          return label;
        }
      } );
  }
````

Since we create a new TickLabelSet, we need to remove the previous verticalTickLabelSet. It is not a pattern that  I used very often, so it would be worth for you to review it for correctness. 
```js
    this.zoomLevelProperty.link( zoomLevel => {

      // spacing between ticks
      const spacing = Math.pow( 2, -zoomLevel + CalculusGrapherConstants.ZOOM_LEVEL_RANGE.defaultValue );

      const maxY = initialMaxY * spacing;

      // set new y range
      this.chartTransform.setModelYRange( new Range( -maxY, maxY ) );

      // change the vertical spacing of the ticks such that there are a constant number of them
      verticalTickMarkSet.setSpacing( spacing );

      // remove previous verticalTickLabelSet and dispose of it
      tickSetNode.removeChild( verticalTickLabelSet );
      verticalTickLabelSet.dispose();

      // create and add a new vertical tick label set with the appropriate label spacing
      verticalTickLabelSet = this.getVerticalTickLabelSet( spacing );
      tickSetNode.addChild( verticalTickLabelSet );

    } );
```


You will notice that I create a new TickLabelSet for each zoomLevel. Initially, I had envisioned that we should create a new TickLabelSet only when the number of decimalPlaces changes. There are currently 9 possible zoom level change and for three of them the number of decimal places changes.  However, that proved to be unnecessary complicated since we needed to keep track of the old number of decimal places and compare it to the new, and then update it. I opted for simplicity and I am generating a new TickLabelSet for each values of zoomLevel instead. 

Assigning for @pixelzoom for review.

**Comment by veillette** [comment]
Reassigning to myself.

I found that there is a method in `Util.js` that gives you the numberOfDecimal places of a value.

Since we dont want the number of decimalPlaces to exceed two,  we could have
```js
decimalPlaces = Math.min(2, Utils.numberOfDecimalPlaces(spacing))
```

**Comment by veillette** [comment]
I addressed the simplification in the commit  above.

**Comment by veillette** [comment]
Assigning to @pixelzoom  and @amanda-phet for review.

**Comment by amanda-phet** [comment]
I agree that a specific range for each zoom level makes sense. When I can load the sim, I'll play around with it and see if I have a suggestion. 

Right now, I'd say any labels are "useful" so someone recognizes that they are zoomed differently than the original f(x) curve, and to get a sense of the scale. However, if there is an obvious range that would be easy to interpret (such as -100 to 100) then I'll try to think of it. The challenge here is that the original range is -7 to 7 in this case. That makes me wonder if we should change the overall scale (both the domain and the range) to fit a better number of boxes. Right now it is a 14x36 grid, right? Maybe 16x40 would be better?

**Comment by veillette** [comment]
It is worth keeping in mind that there are not value labels ( and ticks)
unless you check the box in the preference menu. Since most users will not
turned this on, at first, it is useful to provide some evidence of the
action of the zoom buttons.

I would argue that keeping the spacing between the gridlines fixed ( in
model coordinates) give you a better context of what is going on while
zooming. As you zoom out, the gridlines get closer...

I would say that there may be too many zoom levels.

There doesn't seem to be a pedagogical value in having so many. There is
currently 10 zoom levels for a dynamic range of 2**10 = 1024.

**Comment by veillette** [comment]
Rereading @amanda-phet comment. I think I understand it now. 
She is suggesting to pick new model ranges for the y and x-coordinates such that says the initial ranges (without zooming) still give you "nice" numbers, say y ranging from -10 to 10 and x from 0 to 40,  but while preserving (without zooming) the isometry such that in the view one unit along x is the same length as along y. So we may need to tweak both the model x-y ranges and the size of the view graph.  

I'll note that we can create custom zoom levels, if necessary, such that they dont simply increase by a factor of two every steps. If every third zoom level is a factor of 2.5 instead of 2, it give you a much nicer sequence of 1, 2, 4, 10, 20, 40, 100, etc.

**Comment by amanda-phet** [comment]
Yes @veillette I think you understand what I had in mind. It was just a thought to make the numbers better (for the first three screens, at least). The graphs are currently situated so that there's a lot of space below the graphs, so perhaps we should just increase the height of these graphs so they are -8 to 8 and not worry about the overall scale. The Lab screen is -5 to 5. 

Then we can select "good" zooming in values that work for those two ranges.

**Comment by veillette** [comment]
Assigning back to myself to come with with better values. I'll come back to it later.

For my own self :
2 Graphs : 630x245
3 Graphs : 630x175

**Comment by veillette** [comment]
Here is a proposal for a new range
| # graphs     |  view width -> x Range |      view Height-> y Range model |
| ----------- | ----------- |------------|
|   1             |  612 -> 0 - 50      |  490-> -20 to 20  |   
|   2             |  612 ->0 - 50      |  245-> -10 to 10  |
|   3             |  612-> 0 - 50      |  172-> -7 to 7     |
|   4             |  612-> 0 - 50      |  123-> -5 to 5    |


FYY, here are the constants we set in the simulation

```
  GRAPH_VIEW_WIDTH: 612,

  // vertical height of the graph in model coordinates according to the number of graphs show on the screen
  GRAPH_VERTICAL_HEIGHT: [ 490, 245, 172, 123 ],

  // Ranges
  CURVE_X_RANGE: new Range( 0, 50 ),
```

The model y range is calculated is derived from these three constants, such that it remains isometric when unzoomed.

Although there is no situation of 1 graph or 4 graphs in the sim, we support it for PhET-IO.

![Calculus Grapher screenshot (14)](https://user-images.githubusercontent.com/7633344/204577939-83bd51e0-a86b-47ea-b05d-bb665bacbf83.png)

![Calculus Grapher screenshot (14)](https://user-images.githubusercontent.com/7633344/204579563-5f89d9b7-3eb5-4b44-8b06-fb31f9f79963.png)

![Calculus Grapher screenshot (15)](https://user-images.githubusercontent.com/7633344/204579733-9f06592c-d1da-4037-a62c-4240babf14ae.png)

**Comment by veillette** [comment]
I addressed the comments by @pixelzoom. I reduced the number of  tick marks by half. I allowed up to three decimal places of for the tick labels, witch should take care of the appearance of non-uniformity in the tick range.
I also changed  the zoom level  such that it zoom in/out by 2.5 (instead of 2) every third zoom level. This allowed for increments of 1,2,5,10,20,50,100, etc..., which works well when we start with an initial range of 10.

For two graphs, we have
![image](https://user-images.githubusercontent.com/7633344/206496247-99020831-bebf-4bc2-9083-178fa2cb4364.png)

For three graphs, it doesn't look as nice because of the odd range (initial range of 7),
but it looks acceptable (and only one out of four screens has three graphs)
![image](https://user-images.githubusercontent.com/7633344/206499323-295c465d-cda5-4b62-a311-38e0af54771f.png)

I committed my work this time, I think we are converging to an acceptable solution, and we can refine it as needed.

**Comment by veillette** [comment]
Assigning back to @amanda-phet for review. P.S. it is probably best to test the functionality on master to better get a sense of how it works.

**Comment by amanda-phet** [comment]
This all seems like a huge improvement for the zooming functionality. 

I still have a lingering issue with the placement of the graphs and the variation in their sizes when there are two vs. three graphs visible. Should I open another issue about that?

**Comment by veillette** [comment]
I suggest we open a new issue to tackle the variations in sizes.

**Comment by veillette** [comment]
Assigning back to @amanda-phet to open a new issue about the placement of the graphs and the variation in their sizes when there are two vs. three graphs.

**Comment by veillette** [comment]
We can close this issue then.
